# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07df04ead0b3b042edeb1ea561d301da92720f3cc42b97ea48925adf27bf40736829eb8e340612772dc26738eeafdebcbcc3b957e205dc0d36c3872d1f06a73e

test:
  secret_key_base: a4196ca22feaa2f23925c3e3a69ce9b838e5d882696b0e90af2b7d0f8135b82ae3e07503d47ec40b6c85fd9a5f92823ebbc3254d0dca3379ced8dc440f6186a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
